;;; ghostel-hidden-output-test.el --- Tests for hidden output -*- lexical-binding: t; -*-

;;; Commentary:

;; Hidden output must keep terminal state current without repeating window
;; searches.  Revealing a buffer must restore normal redraw scheduling.

;;; Code:

(require 'ghostel-test-helpers)
(require 'timer)

(defun ghostel-test-hidden-output--count-window-searches (function)
  "Call FUNCTION and return the number of Emacs window searches it makes."
  (let ((searches 0)
        (walk (symbol-function 'walk-windows))
        (windows (symbol-function 'window-list-1))
        (find-window (symbol-function 'get-buffer-window))
        (find-windows (symbol-function 'get-buffer-window-list)))
    (cl-letf (((symbol-function 'walk-windows)
               (lambda (&rest args)
                 (cl-incf searches)
                 (apply walk args)))
              ((symbol-function 'window-list-1)
               (lambda (&rest args)
                 (cl-incf searches)
                 (apply windows args)))
              ((symbol-function 'get-buffer-window)
               (lambda (&rest args)
                 (cl-incf searches)
                 (apply find-window args)))
              ((symbol-function 'get-buffer-window-list)
               (lambda (&rest args)
                 (cl-incf searches)
                 (apply find-windows args))))
      (setq searches 0)
      (funcall function)
      searches)))

(defmacro ghostel-test-hidden-output--with-terminal (spec &rest body)
  "Run BODY with a hidden terminal BUFFER and its pipe PROCESS.
SPEC is (BUFFER PROCESS).  No child program is started."
  (declare (indent 1))
  (pcase-let ((`(,buffer ,process) spec))
    `(save-window-excursion
       (let ((ghostel-buffer-name-function nil)
             (ghostel-enable-url-detection nil)
             (ghostel-enable-file-detection nil)
             (ghostel-detect-password-prompts nil)
             (ghostel-adaptive-fps nil))
         (ghostel-test--with-terminal-buffer (,buffer _term 5 60 100)
           (let ((,process (ghostel-test--dummy-process
                            "ghostel-hidden-output" ,buffer)))
             (setq ghostel--process ,process)
             ,@body))))))

(defmacro ghostel-test-hidden-output--with-timers (timers &rest body)
  "Run BODY with scheduled timer objects collected in TIMERS.
Timers retain the real callback and arguments but run only when the test
invokes them, so a slow test host cannot change the scheduling assertions."
  (declare (indent 1))
  `(let (,timers)
     (cl-letf (((symbol-function 'run-with-timer)
                (lambda (_seconds _repeat function &rest args)
                  (let ((timer (timer-create)))
                    (timer-set-function timer function args)
                    (push timer ,timers)
                    timer))))
       ,@body)))

(defun ghostel-test-hidden-output--fire-timer (timer)
  "Invoke TIMER's recorded callback with its original arguments."
  (apply (timer--function timer) (timer--args timer)))

(ert-deftest ghostel-test-hidden-output-filter-keeps-state-without-window-searches ()
  "Repeated hidden PTY output updates the terminal without window searches."
  :tags '(native)
  (ghostel-test-hidden-output--with-terminal (buffer process)
    (should-not (get-buffer-window buffer t))
    (ghostel--filter process "seed")
    (should ghostel--pending-redraw)
    (let* ((materialized (buffer-string))
           (searches
            (ghostel-test-hidden-output--count-window-searches
             (lambda ()
               (cl-letf (((symbol-function 'run-at-time)
                          (lambda (_seconds _repeat function &rest args)
                            (apply function args))))
                 (dotimes (i 32)
                   (ghostel--filter
                    process
                    (format "\e]2;hidden-title-%d\a\r\e[2Khidden-value-%d" i i))
                   (should (equal ghostel--title (format "hidden-title-%d" i)))
                   (should (equal (ghostel-test--row0 ghostel--term)
                                  (format "hidden-value-%d" i)))))))))
      (should (equal (buffer-string) materialized))
      (should ghostel--pending-redraw)
      (should-not ghostel--redraw-timer)
      (should (= searches 0)))))

(ert-deftest ghostel-test-hidden-output-events-keep-callbacks-without-window-searches ()
  "Repeated hidden native events dispatch callbacks without window searches."
  (with-temp-buffer
    (ghostel-mode)
    (let ((buffer (current-buffer))
          (ghostel-buffer-name-function nil))
      (cl-letf (((symbol-function 'process-buffer) (lambda (_) buffer)))
        (ghostel--events-filter 'pipe "(ghostel--set-title \"seed\")")
        (should ghostel--pending-redraw)
        (let ((searches
               (ghostel-test-hidden-output--count-window-searches
                (lambda ()
                  (dotimes (i 32)
                    (let ((title (format "event-title-%d" i)))
                      (ghostel--events-filter
                       'pipe (format "(ghostel--set-title %S)" title))
                      (should (equal ghostel--title title))))))))
          (should-not ghostel--event-buf)
          (should ghostel--pending-redraw)
          (should-not ghostel--redraw-timer)
          (should (= searches 0)))))))

(ert-deftest ghostel-test-hidden-output-cancels-timer-and-reveals-latest ()
  "Hiding cancels queued rendering; redisplay materializes the latest output."
  :tags '(native)
  (ghostel-test-hidden-output--with-terminal (buffer process)
    (let* ((window (selected-window))
           (previous-buffer (window-buffer window))
           (cancel (symbol-function 'cancel-timer))
           cancelled)
      (ghostel-test-hidden-output--with-timers timers
        (cl-letf (((symbol-function 'cancel-timer)
                   (lambda (timer)
                     (push timer cancelled)
                     (funcall cancel timer))))
          (set-window-buffer window buffer)
          (ghostel--filter process "queued-visible-output")
          (should (= (length timers) 1))
          (let ((queued ghostel--redraw-timer))
            (should (timerp queued))
            (set-window-buffer window previous-buffer)
            (ghostel--filter process "\r\e[2Kfirst-hidden-output")
            (ghostel--filter process "\r\e[2Klatest-hidden-output")
            (should (memq queued cancelled))
            (should ghostel--pending-redraw)
            (should-not ghostel--redraw-timer)
            (should (= (length timers) 1))
            (should-not (string-match-p "latest-hidden-output" (buffer-string)))
            (set-window-buffer window buffer)
            (run-hook-with-args 'pre-redisplay-functions window)
            (should (string-match-p "latest-hidden-output" (buffer-string)))
            (should-not (string-match-p "queued-visible-output\\|first-hidden-output"
                                        (buffer-string)))
            (should-not ghostel--pending-redraw)
            (should-not ghostel--redraw-timer)))))))

(ert-deftest ghostel-test-hidden-output-visible-bulk-reuses-timer-after-reveal ()
  "After reveal, visible bulk output shares one timer and renders its tail."
  :tags '(native)
  (ghostel-test-hidden-output--with-terminal (buffer process)
    (ghostel--filter process "hidden-seed")
    (set-window-buffer (selected-window) buffer)
    (run-hook-with-args 'pre-redisplay-functions (selected-window))
    (should (string-match-p "hidden-seed" (buffer-string)))
    (ghostel-test-hidden-output--with-timers timers
      (dotimes (i 8)
        (ghostel--filter process (format "\r\e[2Kvisible-value-%d" i)))
      (should (= (length timers) 1))
      (should (eq ghostel--redraw-timer (car timers)))
      (should-not (string-match-p "visible-value-7" (buffer-string)))
      (ghostel-test-hidden-output--fire-timer (car timers))
      (should (string-match-p "visible-value-7" (buffer-string)))
      (should-not (string-match-p "hidden-seed" (buffer-string)))
      (should-not ghostel--pending-redraw)
      (should-not ghostel--redraw-timer))))

(ert-deftest ghostel-test-hidden-output-sync-completion-schedules-after-reveal ()
  "A visible buffer resumes rendering when its hidden synchronized frame ends."
  :tags '(native)
  (ghostel-test-hidden-output--with-terminal (buffer process)
    (let ((window (selected-window))
          (previous-buffer (window-buffer (selected-window))))
      (set-window-buffer window buffer)
      (ghostel--write-vt ghostel--term "baseline-frame")
      (ghostel--redraw-now buffer)
      (should (string-match-p "baseline-frame" (buffer-string)))
      (set-window-buffer window previous-buffer)
      (ghostel--filter process "\e[?2026h\r\e[2Kunfinished-frame")
      (ghostel--filter process "\r\e[2Kcompleted-frame")
      (should (ghostel--mode-enabled ghostel--term 2026))
      (should ghostel--pending-redraw)
      (set-window-buffer window buffer)
      (run-hook-with-args 'pre-redisplay-functions window)
      (should (string-match-p "baseline-frame" (buffer-string)))
      (should-not (string-match-p "completed-frame" (buffer-string)))
      (should ghostel--pending-redraw)
      (ghostel-test-hidden-output--with-timers timers
        (ghostel--filter process "\e[?2026l")
        (should-not (ghostel--mode-enabled ghostel--term 2026))
        (should (= (length timers) 1))
        (ghostel-test-hidden-output--fire-timer (car timers))
        (should (string-match-p "completed-frame" (buffer-string)))
        (should-not (string-match-p "baseline-frame" (buffer-string)))
        (should-not ghostel--pending-redraw)
        (should-not ghostel--redraw-timer)))))

(ert-deftest ghostel-test-hidden-output-input-echo-flushes-timer-after-reveal ()
  "Input still reaches the PTY and its visible echo bypasses a queued timer."
  :tags '(native)
  (ghostel-test-hidden-output--with-terminal (buffer process)
    (ghostel--filter process "hidden-seed")
    (set-window-buffer (selected-window) buffer)
    (run-hook-with-args 'pre-redisplay-functions (selected-window))
    (let ((ghostel-immediate-redraw-interval 0.05)
          sent)
      (ghostel-test-hidden-output--with-timers timers
        (ghostel--filter process "\r\e[2Kbackground-output")
        (should (= (length timers) 1))
        (should ghostel--redraw-timer)
        (cl-letf (((symbol-function 'current-time)
                   (lambda () (seconds-to-time 1000)))
                  ((symbol-function 'ghostel--write-pty)
                   (lambda (term text) (push (cons term text) sent))))
          (ghostel--send-string "x")
          (should (equal sent (list (cons ghostel--term "x"))))
          (ghostel--filter process "x")
          (should (string-match-p "background-outputx" (buffer-string)))
          (should (= (length timers) 1))
          (should-not ghostel--pending-redraw)
          (should-not ghostel--redraw-timer))))))

(ert-deftest ghostel-test-hidden-output-send-string-echo-before-redisplay ()
  "Raw input echo renders immediately after reveal, before redisplay hooks."
  :tags '(native)
  (ghostel-test-hidden-output--with-terminal (buffer process)
    (ghostel--filter process "hidden-seed")
    (should ghostel--pending-redraw)
    (should-not (string-match-p "hidden-seed" (buffer-string)))
    (set-window-buffer (selected-window) buffer)
    (let ((ghostel-immediate-redraw-interval 0.05)
          sent)
      (ghostel-test-hidden-output--with-timers timers
        (cl-letf (((symbol-function 'current-time)
                   (lambda () (seconds-to-time 1000)))
                  ((symbol-function 'process-send-string)
                   (lambda (target text) (push (cons target text) sent))))
          (ghostel--send-string "x")
          (should (equal sent (list (cons process "x"))))
          (ghostel--filter process "x")
          (should (string-match-p "hidden-seedx" (buffer-string)))
          (should-not timers)
          (should-not ghostel--pending-redraw)
          (should-not ghostel--redraw-timer))))))

(ert-deftest ghostel-test-hidden-output-encoded-key-echo-before-redisplay ()
  "Encoded input echo before redisplay cancels a redraw queued while hidden."
  :tags '(native)
  (ghostel-test-hidden-output--with-terminal (buffer process)
    (ghostel--filter process "hidden-seed")
    (should ghostel--pending-redraw)
    (ghostel-test-hidden-output--with-timers timers
      (let ((ghostel-inhibit-redraw-functions (list (lambda (_) t))))
        (ghostel--redraw-now buffer))
      (should (= (length timers) 1))
      (let ((queued ghostel--redraw-timer)
            (cancel (symbol-function 'cancel-timer))
            (ghostel-immediate-redraw-interval 0.05)
            cancelled
            sent)
        (should (timerp queued))
        (should-not (string-match-p "hidden-seed" (buffer-string)))
        (set-window-buffer (selected-window) buffer)
        (cl-letf (((symbol-function 'current-time)
                   (lambda () (seconds-to-time 1000)))
                  ((symbol-function 'process-send-string)
                   (lambda (target text) (push (cons target text) sent)))
                  ((symbol-function 'ghostel--send-string)
                   (lambda (&rest _)
                     (ert-fail "Single-character key used the raw fallback")))
                  ((symbol-function 'cancel-timer)
                   (lambda (timer)
                     (push timer cancelled)
                     (funcall cancel timer))))
          (ghostel--send-encoded "x" "")
          (should (equal sent (list (cons process "x"))))
          (ghostel--filter process "x")
          (should (string-match-p "hidden-seedx" (buffer-string)))
          (should (memq queued cancelled))
          (should (= (length timers) 1))
          (should-not ghostel--pending-redraw)
          (should-not ghostel--redraw-timer))))))

(ert-deftest ghostel-test-hidden-output-title-state-and-name-callback-stay-current ()
  "Hidden title events still rename the buffer and support direct formatting."
  :tags '(native)
  (ghostel-test-hidden-output--with-terminal (buffer process)
    (let* ((window (selected-window))
           (previous-buffer (window-buffer window))
           (ghostel-buffer-identification-format "%t")
           (titles nil)
           (ghostel-buffer-name-function
            (lambda (title)
              (push title titles)
              (format " *ghostel-hidden-title-%s*" title))))
      (set-window-buffer window buffer)
      (ghostel--set-title "baseline-title")
      (should (equal mode-line-buffer-identification '("baseline-title")))
      (set-window-buffer window previous-buffer)
      (ghostel--filter process "hidden-output")
      (should ghostel--pending-redraw)
      (dolist (title '("first-hidden-title" "latest-hidden-title"))
        (ghostel--events-filter
         process (format "(ghostel--set-title %S)" title))
        (should (equal ghostel--title title))
        (should (equal (buffer-name buffer)
                       (format " *ghostel-hidden-title-%s*" title)))
        (should (equal (ghostel--buffer-identification "%t") (list title))))
      (should (equal (nreverse titles)
                     '("baseline-title" "first-hidden-title"
                       "latest-hidden-title")))
      (should-not (get-buffer-window buffer t)))))

(ert-deftest ghostel-test-hidden-output-identification-refreshes-on-reveal ()
  "Redisplay refreshes the latest hidden title, even after input was sent."
  :tags '(native)
  (dolist (input '(none raw encoded))
    (ert-info ((format "input before redisplay: %s" input))
      (ghostel-test-hidden-output--with-terminal (buffer process)
        (let ((window (selected-window))
              (previous-buffer (window-buffer (selected-window)))
              (ghostel-buffer-identification-format "%t")
              sent)
          (set-window-buffer window buffer)
          (ghostel--set-title "baseline-title")
          (should (equal mode-line-buffer-identification '("baseline-title")))
          (set-window-buffer window previous-buffer)
          (ghostel--filter process "hidden-output")
          (should ghostel--pending-redraw)
          (ghostel--events-filter
           process "(ghostel--set-title \"latest-hidden-title\")")
          (should (equal ghostel--title "latest-hidden-title"))
          (set-window-buffer window buffer)
          (cl-letf (((symbol-function 'process-send-string)
                     (lambda (target text) (push (cons target text) sent))))
            (pcase input
              ('raw (ghostel--send-string "x"))
              ('encoded
               (cl-letf (((symbol-function 'ghostel--send-string)
                          (lambda (&rest _)
                            (ert-fail "Encoded key used the raw fallback"))))
                 (ghostel--send-encoded "x" ""))))
            (should (equal sent (unless (eq input 'none)
                                  (list (cons process "x"))))))
          (run-hook-with-args 'pre-redisplay-functions window)
          (should (equal mode-line-buffer-identification
                         '("latest-hidden-title")))
          (should (string-match-p "hidden-output" (buffer-string)))
          (should-not ghostel--pending-redraw))))))

(provide 'ghostel-hidden-output-test)
;;; ghostel-hidden-output-test.el ends here
